[package]
name = "syncstorage"
version = "0.1.0"
license = "MPL-2.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[profile.release]
# Enables line numbers in Sentry
debug = 1

[dependencies]
#actix = "0.8"
actix-cors ="0.1"
actix-web = "1.0"
actix-rt = "0.2"
actix-http-test = {version="0.2.0", features=["ssl"]}
actix-http = "0.2"
actix-service= "0.4"
base64 = "0.10.1"
cadence = "0.17.1"
chrono = "0.4"
config = "0.9.3"
diesel = { version = "1.4.2", features = ["mysql", "r2d2"] }
diesel_logger = "0.1.0"
diesel_migrations = { version = "1.4.0", features = ["mysql"] }
docopt = "1.1.0"
env_logger = "0.6.1"
failure = "0.1.5"
futures = "0.1"
lazy_static = "1.3.0"
# TODO: switch back to default (use_ring) after the actix-web 1.0 upgrade
hawk = { version = "3.0.0", default_features = false, features = ["use_ring"] }
hkdf = "0.7.0"
hmac = "0.7.0"
mozsvc-common = "0.1"
num = "0.2.0"
num_cpus = "1.10"
rand = "0.6.5"
regex = "1.1"
sentry = "0.15.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.39"
sha2 = "0.8.0"
time = "0.1.42"
tokio-threadpool = "0.1.14"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
validator = "0.8.0"
validator_derive = "0.8.0"
